add wizard to create parcels from previous crop
NaN-tic/trytond-agronomics pull request #21
Opened 2022-10-17 07:37 UTC by angelnan

2023-01-11 10:23 UTC, albertca requested changes
Falta el test

2023-03-15 17:15 UTC, raimonesteve commented on plot.py
> +
Abans de la class, dos intros.

2023-03-15 17:15 UTC, raimonesteve commented on plot.py
> +
Abans de la class, dos intros.

2023-03-15 17:15 UTC, raimonesteve commented on plot.py
> +    'New Version'
'Create New Parcels'

Potser tb la classe dir-li en plural: CreateNewParcels, com està dient al ``__name__`` i el botó "copy_parcels" (usar mateixa nomenclatura).

2023-03-15 17:15 UTC, raimonesteve commented on plot.py
> +    "Create New Parcel - Start"
Idem. mateix patró pel nom de classes & co.

2023-03-15 17:15 UTC, raimonesteve commented on plot.py
Abans de la class, dos intros.

2023-03-22 08:08 UTC, merged