Add cron to deactivate variants with stock 0 | #046284
NaN-tic/trytond-agronomics pull request #6
Opened 2021-12-23 13:13 UTC by jared-nan

2021-12-24 08:19 UTC, raimonesteve commented on locale/ca.po
> +#, fuzzy
atenció als fuzzy!

2021-12-24 08:19 UTC, raimonesteve commented on locale/es.po
> +msgid "Default cost distribution template"
Plantilla de distribución de costos predeterminada

2021-12-24 08:19 UTC, raimonesteve commented on locale/ca.po
>  msgstr "Plantacións"
Plantació

2021-12-24 08:19 UTC, raimonesteve commented on locale/ca.po
>  msgstr "Productes"
Producte

2021-12-24 08:19 UTC, raimonesteve commented on locale/ca.po
> +msgstr "Desactivar Variants"
Desactivar variants

2021-12-24 08:19 UTC, raimonesteve commented on locale/es.po
> +msgstr "Desactivar variante con estoc 0"
Desactivar variante con stock a 0

2021-12-24 08:19 UTC, raimonesteve commented on locale/ca.po
> +msgstr "Desactivar variant amb estoc 0"
Desactivar variant amb estoc a 0

2021-12-24 08:19 UTC, raimonesteve commented on locale/es.po
> +#, fuzzy
atenció fuzzy

2021-12-24 08:19 UTC, raimonesteve commented on locale/es.po
> +msgstr "Distribución de costos"
Distribución de costes

2021-12-24 08:19 UTC, raimonesteve commented on product.py
> +from trytond.pool import PoolMeta, Pool
from trytond.pool import Pool, PoolMeta

(ordre alfabétic)

2021-12-24 08:19 UTC, raimonesteve commented on product.py
> +    variant_deactivation_time = fields.TimeDelta('Variant Deactivation Time')
("Variant Deactivation Time")

amb doble cometa. Es una decissió de "core". hi han mes camps....

2021-12-24 08:19 UTC, raimonesteve commented on product.py
> +    variant_deactivate_stock_zero = fields.Boolean('Variant Deactivate Stock 0')
("Variant Deactivate Stock 0")

2022-01-18 23:06 UTC, albertca requested changes

2022-01-18 23:06 UTC, albertca commented on product.py
> +                        (datetime.now() - config.variant_deactivation_time))
You should check if variant_deactivation_time is None and do nothing instead of crashing.

2022-01-20 12:14 UTC, albertca approved these changes

2022-01-25 09:29 UTC, merged